# Generated by Django 4.2.20 on 2025-03-08 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataentry',
            name='file',
            field=models.CharField(default='', max_length=64),
        ),
    ]
