# Generated by Django 4.2.20 on 2025-03-09 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_dataentry_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataentry',
            name='file_realid',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='dataentry',
            name='create_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='dataentry',
            name='file',
            field=models.FileField(default=None, null=True, upload_to=''),
        ),
    ]
