# Generated by Django 4.2.20 on 2025-03-09 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_dataentry_file_realid_alter_dataentry_create_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataentry',
            name='file',
            field=models.FileField(blank=True, default=None, null=True, upload_to='static/uploads'),
        ),
    ]
