# Generated by Django 4.2.20 on 2025-03-09 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_dataentry_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataentry',
            name='thumbnail',
            field=models.CharField(default=None, max_length=64, null=True),
        ),
    ]
