# Generated by Django 4.2.20 on 2025-03-10 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_dataentry_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataentry',
            name='title',
            field=models.CharField(default='', max_length=64),
        ),
    ]
